name = "fast-proof-theory"
version = "0.1.0"
srcDir = "."
defaultTargets = ["fast-proof-theory"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.29.0"

[[lean_lib]]
name = "FastProofTheory"

[[lean_exe]]
name = "fast-proof-theory"
root = "FastProofTheory.App.Main"

[[lean_exe]]
name = "mypa-lean-kernel"
root = "FastProofTheory.App.LeanKernelMain"

[[lean_exe]]
name = "mypa-check"
root = "FastProofTheory.App.MypaCheckMain"

[[lean_exe]]
name = "mypa-export"
root = "FastProofTheory.App.MypaExportMain"

[[lean_exe]]
name = "mypa-export-cache"
root = "FastProofTheory.App.MypaExportCacheMain"
